import type { Executor } from "./db";

/**
 * スキーマ。PostgreSQL。
 *
 * すべて IF NOT EXISTS で書いてあるので、何度流しても構わない。
 */
export const SCHEMA = `
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  handle        TEXT NOT NULL UNIQUE,
  display_name  TEXT NOT NULL,
  bio           TEXT NOT NULL DEFAULT '',
  password_hash TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 作品（小説・アニメ・漫画・映画）
CREATE TABLE IF NOT EXISTS works (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  title       TEXT NOT NULL,
  author      TEXT NOT NULL,
  medium      TEXT NOT NULL DEFAULT 'novel',
  year        INTEGER,
  description TEXT NOT NULL DEFAULT '',
  created_by  INTEGER REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 実在の場所（＝事典の項目）
CREATE TABLE IF NOT EXISTS places (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  lat        DOUBLE PRECISION NOT NULL,
  lng        DOUBLE PRECISION NOT NULL,
  prefecture TEXT NOT NULL DEFAULT '',
  address    TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  access     TEXT NOT NULL DEFAULT '',
  photo_path TEXT NOT NULL DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  updated_by INTEGER REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_places_name ON places(name);

-- 作中の記述（本文の一節・シーン）
CREATE TABLE IF NOT EXISTS passages (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_id       INTEGER NOT NULL REFERENCES works(id) ON DELETE CASCADE,
  chapter       TEXT NOT NULL DEFAULT '',
  kind          TEXT NOT NULL DEFAULT 'text',
  quote         TEXT NOT NULL,
  note          TEXT NOT NULL DEFAULT '',
  sort_order    INTEGER NOT NULL DEFAULT 0,
  image_path    TEXT NOT NULL DEFAULT '',
  image_caption TEXT NOT NULL DEFAULT '',
  image_credit  TEXT NOT NULL DEFAULT '',
  created_by    INTEGER REFERENCES users(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ,
  updated_by    INTEGER REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_passages_work ON passages(work_id);

-- 比定（この記述はこの場所だ、という結びつけ）
CREATE TABLE IF NOT EXISTS identifications (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_id INTEGER NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
  place_id   INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  rationale  TEXT NOT NULL DEFAULT '',
  evidence   TEXT NOT NULL DEFAULT 'guess',
  source_url TEXT NOT NULL DEFAULT '',
  created_by INTEGER REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (passage_id, place_id)
);
CREATE INDEX IF NOT EXISTS idx_ident_passage ON identifications(passage_id);
CREATE INDEX IF NOT EXISTS idx_ident_place ON identifications(place_id);

-- 支持／不支持
CREATE TABLE IF NOT EXISTS votes (
  identification_id INTEGER NOT NULL REFERENCES identifications(id) ON DELETE CASCADE,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  value             INTEGER NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (identification_id, user_id)
);

-- 議論
CREATE TABLE IF NOT EXISTS comments (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_id        INTEGER NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
  identification_id INTEGER REFERENCES identifications(id) ON DELETE CASCADE,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  body              TEXT NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_comments_passage ON comments(passage_id);

-- 場所の記事の版
CREATE TABLE IF NOT EXISTS place_revisions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id   INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  editor_id  INTEGER REFERENCES users(id),
  name       TEXT NOT NULL,
  lat        DOUBLE PRECISION NOT NULL,
  lng        DOUBLE PRECISION NOT NULL,
  prefecture TEXT NOT NULL DEFAULT '',
  address    TEXT NOT NULL DEFAULT '',
  note       TEXT NOT NULL DEFAULT '',
  body       TEXT NOT NULL DEFAULT '',
  access     TEXT NOT NULL DEFAULT '',
  photo_path TEXT NOT NULL DEFAULT '',
  summary    TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_revisions_place ON place_revisions(place_id, id DESC);

-- シーンの版
CREATE TABLE IF NOT EXISTS passage_revisions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  passage_id    INTEGER NOT NULL REFERENCES passages(id) ON DELETE CASCADE,
  editor_id     INTEGER REFERENCES users(id),
  chapter       TEXT NOT NULL DEFAULT '',
  kind          TEXT NOT NULL DEFAULT 'scene',
  quote         TEXT NOT NULL,
  note          TEXT NOT NULL DEFAULT '',
  image_path    TEXT NOT NULL DEFAULT '',
  image_caption TEXT NOT NULL DEFAULT '',
  image_credit  TEXT NOT NULL DEFAULT '',
  summary       TEXT NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_prev_passage ON passage_revisions(passage_id, id DESC);

-- 場所への「いいね」
CREATE TABLE IF NOT EXISTS place_likes (
  place_id   INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (place_id, user_id)
);

-- 適用済みのデータパック
CREATE TABLE IF NOT EXISTS data_packs (
  id         TEXT PRIMARY KEY,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
`;

export async function createSchema(x: Executor) {
  await x.exec(SCHEMA);
}
